### ISSUE TITLE
Issue with users table not having name column

### ISSUE THREAD

**Issue by ketchalegend** [amendozaaguiar/filament-route-statistics#1]
* When i configure your plugin, i get the error regarding my user model not having a column `name` I just have first_name & last_name fields. My work around was to extend your resource and make the changes there. Maybe think of using `email` instead. It could be a problem for others. 

```
                SelectFilter::make('user_id')
                    ->label(trans('filament-route-statistics::filament-route-statistics.table.columns.user'))
                    ->multiple()
                    ->options(fn () => User::select('id', 'email')->pluck('email', 'id')->toArray())
                    ->attribute('user_id'),
```

```
                TextColumn::make('user.email')
                    ->label(trans('filament-route-statistics::filament-route-statistics.table.columns.user.email'))
                    ->searchable()
                    ->sortable(),
```

This are my changes which solve the issue. Not everyone has a column name.

**Comment by amendozaaguiar** [comment]
Added the feature to specify the column in the user relationship to be displayed in the table (commit [6efcb6b](https://github.com/amendozaaguiar/filament-route-statistics/commit/63698bbf660d8b3c56f54462fab435dfe58e800a)). This enhancement is reflected in the `config\filament-route-statistics.php` file, with the following code snippet:

```php
return [
    'sort' => [
        'column' => 'id',
        'direction' => 'desc',
    ],
    'username' => [
        'column' => 'email'
    ]
];
```
Thank you for your contribution! 🙌

**Comment by ketchalegend** [comment]
Awesome thank you! Great job! 🚀
