### ISSUE TITLE
Unable to add to Group Navigation.

### ISSUE THREAD

**Issue by thedanmwangi** [amendozaaguiar/filament-route-statistics#2]
Hello, this package is a life saver. Thank you for that.

But I am unable to change the appearance and look of the package. For example, I cannot change the name of the Group Navigation, I cannot change the route name, I cannot change the icon.

Could this be an update that is soon coming?

Otherwise, thanks!

**Comment by joshuahay** [comment]
@amendozaaguiar If you publish the translations you can edit some of the navigation settings such as Group and Labels.

**Comment by thedanmwangi** [comment]
> @amendozaaguiar If you publish the translations you can edit some of the navigation settings such as Group and Labels.

This would be a great way to achieve some level of customization.

**Comment by amendozaaguiar** [comment]
The feature to specify the navigation icon and customize the slug was added in commit [b135040](https://github.com/amendozaaguiar/filament-route-statistics/commit/b1350405140c7ff4a83cc590d2a7ad599ea321d6), This enhancement is reflected in the file config\filament-route-statistics.php.

Navigation labels can be customized in the translation files. Remember, you can use the `php artisan vendor:publish --tag="filament-route-statistics-translations"` command to publish them.

Thank you for your contribution! 🙌

**Comment by gavinhewitt** [comment]
Hi,

This option was removed? There's no config and no option to set the NavigationGroup :-(

**Comment by amendozaaguiar** [comment]
@gavinhewitt The package has been updated and now it extends from Page, allowing you to use the Navigation documentation: [Navigation Documentation](https://filamentphp.com/docs/3.x/panels/navigation) to create navigation groupings.

**Comment by gavinhewitt** [comment]
> @gavinhewitt The package has been updated and now it extends from Page, allowing you to use the Navigation documentation: [Navigation Documentation](https://filamentphp.com/docs/3.x/panels/navigation) to create navigation groupings.

Thank you, but if I understand correctly, in order to change the group you have to manually (re)create the groupings in the panel serviceprovider? If not, can you provide an example of how you'd do it?

**Comment by amendozaaguiar** [comment]
> > @gavinhewitt The package has been updated and now it extends from Page, allowing you to use the Navigation documentation: [Navigation Documentation](https://filamentphp.com/docs/3.x/panels/navigation) to create navigation groupings.
> 
> Thank you, but if I understand correctly, in order to change the group you have to manually (re)create the groupings in the panel serviceprovider? If not, can you provide an example of how you'd do it?

You can override the `protected static ?string $navigationGroup = 'YOUR_CUSTOM_GROUP';` variable. [Reference](https://filamentphp.com/docs/3.x/panels/navigation#grouping-navigation-items)

**Comment by gavinhewitt** [comment]
Thanks, I know how to override variables. The point however is that I don't see/know how to override them in a plugin. Unless you mean that you have to extend the plugin?

**Comment by amendozaaguiar** [comment]
> Thanks, I know how to override variables. The point however is that I don't see/know how to override them in a plugin. Unless you mean that you have to extend the plugin?

Yes, you must extend the plugin to customize the plugin according to your needs.

**Comment by gavinhewitt** [comment]
That's what I thought. Wouldn't it be more convenient for developers to just have a function that sets it instead of having to extend the plugin? Ie:

```php
$panel
    ->plugins([
        FilamentRouteStatisticsPlugin::make()
               ->navigationGroup('Whatever')
               ->navigationSort(3)
               ->registerNavigation(false)
               // etc.
        ]);
```

**Comment by blackforestcode** [comment]
> That's what I thought. Wouldn't it be more convenient for developers to just have a function that sets it instead of having to extend the plugin? Ie:
> 
> ```
> $panel
>     ->plugins([
>         FilamentRouteStatisticsPlugin::make()
>                ->navigationGroup('Whatever')
>                ->navigationSort(3)
>                ->registerNavigation(false)
>                // etc.
>         ]);
> ```

That would be great. Or at least a (currently not available) customizable config file.
