### ISSUE TITLE
Support for laravel-route-statistics v3.0.0 

### ISSUE THREAD

**Issue by jhoanborges** [amendozaaguiar/filament-route-statistics#3]
laravel-route-statistics v3.0.0  is out. It'll be great to have support for this version.

![image](https://github.com/amendozaaguiar/filament-route-statistics/assets/32471957/aeb64d7a-c05c-4ff0-b5ef-13c8d6e662a8)

**Comment by amendozaaguiar** [comment]
Great news! Support for [Laravel Route Statistics v3](https://github.com/bilfeldt/laravel-route-statistics) has been added in commit [b6f664a](https://github.com/amendozaaguiar/filament-route-statistics/commit/b6f664acb4c2213a4766b89689743d7a129da262).

Thank you for your contribution! 🙌
