### ISSUE TITLE
Where is the database migration ?

### ISSUE THREAD

**Issue by baraakhateeb** [amendozaaguiar/filament-route-statistics#9]
Base table or view not found: 1146 Table 'pts_db.route_statistics' doesn't exist,
thanks in advance

**Comment by amendozaaguiar** [comment]
> Base table or view not found: 1146 Table 'pts_db.route_statistics' doesn't exist, thanks in advance

Remember to install the package beforehand: [laravel-route-statistics](https://github.com/bilfeldt/laravel-route-statistics).

**Comment by blackforestcode** [comment]
> > Base table or view not found: 1146 Table 'pts_db.route_statistics' doesn't exist, thanks in advance
> 
> Remember to install the package beforehand: [laravel-route-statistics](https://github.com/bilfeldt/laravel-route-statistics).

That should be mentioned in the Plugin documentation.
